//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServisFemsJup
{
    using System;
    using System.Collections.Generic;
    
    public partial class actividadesPublicacion
    {
        public int id { get; set; }
        public int idpublicacion { get; set; }
        public int idactivid { get; set; }
    
        public virtual actividade actividade { get; set; }
        public virtual publicacion publicacion { get; set; }
    }
}
