//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServisFemsJup
{
    using System;
    using System.Collections.Generic;
    
    public partial class publicacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public publicacion()
        {
            this.actividadesPublicacions = new HashSet<actividadesPublicacion>();
            this.solicituds = new HashSet<solicitud>();
        }
    
        public int id { get; set; }
        public int idcategorias { get; set; }
        public int idusuario { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fecha { get; set; }
        public int tarifa { get; set; }
        public string extra { get; set; }
        public int estatus { get; set; }
        public string dispo { get; set; }
        public string @long { get; set; }
        public string lat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<actividadesPublicacion> actividadesPublicacions { get; set; }
        public virtual categoriaT categoriaT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<solicitud> solicituds { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
