//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServisFemsJup
{
    using System;
    using System.Collections.Generic;
    
    public partial class elementopermiso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public elementopermiso()
        {
            this.elementopermitidoes = new HashSet<elementopermitido>();
        }
    
        public int id { get; set; }
        public Nullable<int> idelemento { get; set; }
        public Nullable<int> idpermiso { get; set; }
    
        public virtual elemento elemento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<elementopermitido> elementopermitidoes { get; set; }
        public virtual permiso permiso { get; set; }
    }
}
