//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServisFemsJup
{
    using System;
    using System.Collections.Generic;
    
    public partial class insidencia
    {
        public int id { get; set; }
        public int idusuario { get; set; }
        public int idusreportado { get; set; }
        public string mensaje { get; set; }
        public int estatus { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<int> tipo { get; set; }
    
        public virtual usuario usuario { get; set; }
        public virtual usuario usuario1 { get; set; }
    }
}
